## Fundaments of Pytorch

Ref notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/

In [1]:
print("Hello PyTorch!")

Hello PyTorch!


In [2]:
!nvidia-smi

Mon Mar 18 02:14:31 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   55C    P8              10W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [3]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [4]:
print(torch.__version__)

2.2.1+cu121


## Introduction to Tensors

### Creating Tensors

In [5]:
# Creating tensors

#1. Scalar
scalar=torch.tensor(7)
scalar

tensor(7)

In [6]:
#Number of dimensions
scalar.ndim

0

In [7]:
#Get tensor back as python int
scalar.item()

7

In [8]:
#vector
vector=torch.tensor([7,7])
vector

tensor([7, 7])

In [9]:
vector.ndim

1

In [10]:
vector[0]

tensor(7)

In [11]:
# throws error: vector.item()
vector.shape

torch.Size([2])

In [12]:
#Matrix (usually uppercase)
MATRIX = torch.tensor([[7,8],
                       [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [13]:
MATRIX.ndim

2

In [14]:
MATRIX[0]

tensor([7, 8])

In [15]:
MATRIX.shape

torch.Size([2, 2])

In [16]:
# Tensor (usually uppercase)

TENSOR = torch.tensor([[[1,2,3,4],
                        [5,6,7,8],
                        [9,10,11,12]],
                       [[1,1,1,1],
                        [2,2,2,2],
                        [3,3,3,3]

                        ]])
TENSOR

tensor([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],

        [[ 1,  1,  1,  1],
         [ 2,  2,  2,  2],
         [ 3,  3,  3,  3]]])

In [17]:
TENSOR.shape

torch.Size([2, 3, 4])

In [18]:
TENSOR.ndim

3

In [19]:
TENSOR[0]

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])

### Random Tensors

why Random tensors?
They are important bcz the way many NN learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.
`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

In [20]:
# Create a random tensor of shape/size  (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.3883, 0.6747, 0.9275, 0.4309],
        [0.1535, 0.3190, 0.0725, 0.6020],
        [0.5653, 0.4884, 0.9451, 0.5854]])

In [21]:
random_tensor.ndim

2

In [22]:
# create a random tensor with similar shape to an image tensor
random_image_sized_tensor = torch.rand(size=(3, 224,224)) #  color channels, height, width
random_image_sized_tensor.shape, random_image_sized_tensor.ndim

(torch.Size([3, 224, 224]), 3)

### Zeros and ones

In [23]:
# Create a tensor of all zeroes (used to create a mask)
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [24]:
# craete a tensor of all ones
ones= torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [25]:
# default datatype of all tensors is float32!!
ones.dtype

torch.float32

### Create a range of tensors and tensors-like

In [26]:
# use torch.range()
one_to_ten= torch.arange(1,11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [27]:
step_tensor = torch.arange(start=1, end=100, step=5)
step_tensor

tensor([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71, 76, 81, 86,
        91, 96])

In [28]:
# Creating tensors-like
ten_zeroes = torch.zeros_like(input=one_to_ten)
ten_zeroes

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor Datatypes

DAtatypes important because of Precision in computing
 **NOTE** Tensor datatypes is one of the three big errors with PyTorch or Deep Learning:
 1. Tensors not right datatype
 2. Tenors not right shape
 3. Tensors not on the right device

In [29]:
# Float 32 tensor (32 is single precision , 16 bit is half precision (faster as takes less memory, but less precision))
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=None)
# default is 32!
float_32_tensor.dtype



torch.float32

In [30]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=torch.float16)
float_16_tensor.dtype

torch.float16

In [31]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, #
                               device=None, # device can be "cpu" or "cuda" (what device is your tensor on)
                               requires_grad=False) # Whether or not to track gradients with this tensors operations
# default is 32!
float_32_tensor.dtype

torch.float32

In [32]:
#Setting a dtype
anothe_float_16 = float_32_tensor.type(torch.float16)
anothe_float_16

tensor([3., 6., 9.], dtype=torch.float16)

In [33]:
multiplied_tensor = float_16_tensor * float_32_tensor
multiplied_tensor, multiplied_tensor.dtype

(tensor([ 9., 36., 81.]), torch.float32)

In [34]:
int_32_tensor = torch.tensor ([3,6,9], dtype=torch.int32)
multiplied_2 = int_32_tensor* float_32_tensor
multiplied_2, multiplied_2.dtype

(tensor([ 9., 36., 81.]), torch.float32)

In [35]:
## Getting information from tensors:
# dtype -> tensor_var.dtype
# shape -> tensor_var.shape
# device ->tensor_var.device

In [36]:
some_tensor = torch.rand(3,4)
some_tensor.dtype, some_tensor.shape, some_tensor.device

(torch.float32, torch.Size([3, 4]), device(type='cpu'))

### Manipulating Tensors

Tensor operations include
* addition
* subtraction
* multiplication (elemnet-wise)
* division
* matrix multiplication

There are two main rules mat mul should satisfy:
1. Inner dimensions must match
* `(3,2) @ (3,2) will not work`
* `(2,3) @ (3,2) will work`
* `(3,2) @ (2,3) will work`
2. The resulting matrix has shape of outer dimensions

In [37]:
# create a tensor and add 10 to it, multiply by 10, subtract 10
tensor = torch.tensor([1,2,3])
tensor + 10, tensor * 10, tensor-10

(tensor([11, 12, 13]), tensor([10, 20, 30]), tensor([-9, -8, -7]))

In [38]:
# Try inbuilt functions of pytorch
torch.mul(tensor, 10), torch.add(tensor, 10)

(tensor([10, 20, 30]), tensor([11, 12, 13]))

In [39]:
# Matrix multiplication
# Two main types of multiplications in deep learning: element wise, matrix multiplication (dot product)


In [40]:
#element wise
tensor*tensor

tensor([1, 4, 9])

In [41]:
#matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [42]:
# @ is symbol for matrix mul
tensor @ tensor

tensor(14)

In [43]:
# Matrix multiplication by hand
1*1 + 2*2 + 3*3

14

In [44]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i]* tensor[i]
print(value)

tensor(14)
CPU times: user 781 µs, sys: 947 µs, total: 1.73 ms
Wall time: 3.25 ms


In [45]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 687 µs, sys: 130 µs, total: 817 µs
Wall time: 794 µs


tensor(14)

### MATMUL IS WAYYYYYYY FASTER! Because of vectorization (instead of using for loops)

### One of the most common errors in Deep Learning: shape errors

In [46]:
#Shapes for mat mul
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])
tensor_B = torch.tensor([[7,10],
                         [8,11],
                         [9,12]])
###ERROR!!!!!!
# torch.mm(tensor_A, tensor_B) #torch.mm is same as/ alias for torch.matmul

To fix our tensor shape issues, we can manipulate the shape of one of our tensors using a transpose

a **Transpose** switches the axes or dimensions of a given tensor


In [47]:
tensor_B.T, tensor_B.T.shape, tensor_B.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]),
 torch.Size([3, 2]))

In [48]:
#The matrix mul operation works when tensor_B is transposed.
torch.mm(tensor_A, tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

### Fidning the min, max, mean, sum, etc (tensor aggregation)

In [49]:
#craete a tensor
X= torch.arange(0,100,10)
X

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [50]:
X.min(), torch.min(X), X.max(), torch.max(X)

(tensor(0), tensor(0), tensor(90), tensor(90))

In [51]:
#mean
##### THROWS ERROR DTYPEEEEEEE!!!!!! torch.mean requires a tensor of float32 datatype to work
# torch.mean(X)
# X.mean()

torch.mean(X.type(torch.float32)), X.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [52]:
# Find the sum
torch.sum(X), X.sum()

(tensor(450), tensor(450))

In [53]:
#finding positional min and max
X.argmin() # Find the position(index) in the tensor that has the minimum value

tensor(0)

In [54]:
X.argmax() #very useful for softmax function

tensor(9)

In [55]:
some_tensor, some_tensor.argmin()

(tensor([[0.5892, 0.4781, 0.3734, 0.3725],
         [0.1681, 0.5172, 0.3256, 0.5754],
         [0.0680, 0.7436, 0.6923, 0.3983]]),
 tensor(8))

### Reshaping, Viewing and Stacking, Squeezing and unsqueezing

* Reshaping -> reshapes an input tensor to defined shape
* View -> Return a view of an input tensor of certain shape but keep the same memory as original tensor
* Stacking -> Combine multiple tensors on top of each other (vstack), or side by side (hstack)
* Squeeze -> removes all `1` dimensions from a tensor
* Unsqueezze -> add a `1` dimension to a target tensor
* Permute -> Return a View of the input with dimensions permuted (swapped) in a certain way

In [56]:
x = torch.arange(1.,10.)
x,x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [57]:
#new dimensions have to be compatible with original dimensions.
x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [58]:
x_reshaped = x.reshape(9,1)
x_reshaped, x_reshaped.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [59]:
#Change the view
z=x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [60]:
#changing z changes x because a view of tensor shares the same memory as original

z[:,0]=5
z,x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [61]:
#stack tensors on top of each other
x_stacked= torch.stack([x,x,x,x], dim=0) #vertical
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [62]:
x_stacked= torch.stack([x,x,x,x], dim=1) #horizontal #dim2 incompatible bcz x only has 0,1 dim
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [63]:
#torch.squeeze removes all single dimensions from target tensor
x_reshaped, x_reshaped.shape

(tensor([[5.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [64]:
x_reshaped.squeeze(), x_reshaped.squeeze().shape

(tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [65]:
print(f"Previous tensor: {x_reshaped}")
print(f"Previous tensor shape: {x_reshaped.shape}")
x_squeezed = x_reshaped.squeeze()
print(f"Squeeze tensor: {x_squeezed}")
print(f"Squeeze tensor shape: {x_squeezed.shape}")

Previous tensor: tensor([[5.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])
Previous tensor shape: torch.Size([9, 1])
Squeeze tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Squeeze tensor shape: torch.Size([9])


In [66]:
#torch.qunsqueeze adds a single dimension to a target tensor at a specific dimension
print(f"previous tensor: {x_squeezed}")
print(f"previous shape: {x_squeezed.shape}")
x_unsqueezed= x_squeezed.unsqueeze(dim=1)
print(f"New tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")
x_unsqueezed= x_squeezed.unsqueeze(dim=0)
print(f"New tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")



previous tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
previous shape: torch.Size([9])
New tensor: tensor([[5.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])
New shape: torch.Size([9, 1])
New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [67]:
#torch.permute rearranges the dimensions of a target tensor in a specified order
#used very much with images
x_orig = torch.rand(size=(224,224, 3)) # heught, widyh, color channels
#Permute the orig to rearrange the axis(or dim) order
x_permuted = x_orig.permute(2,0,1) #shifts 0->1, 1->2, 2->0

"""since permute is a view, they share memory, if you chnage an elemnt in one,
it changes in both"""
x_orig.shape, x_permuted.shape


(torch.Size([224, 224, 3]), torch.Size([3, 224, 224]))

### Indexing(selecting data from tensors)

Indexing with pytorch is similar to indexing with numpy

In [68]:
x=torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [69]:
x[0] #first bracket

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [70]:
x[0][0], x[0,0] #same # middle bracket

(tensor([1, 2, 3]), tensor([1, 2, 3]))

In [71]:
x[0,0,0] #last bracket

tensor(1)

In [72]:
x[0,1,1], x[0][2][2]

(tensor(5), tensor(9))

In [73]:
#: to select all of target dim
x[:,0]

tensor([[1, 2, 3]])

In [74]:
x[:,:,1] #get all values of 0th and 1st dim but only index 1 of the second dim


tensor([[2, 5, 8]])

In [75]:
#get all values of the 0 dimension but only the 1 index value of 1st and 2nd dimension
x[:,1,1]

tensor([5])

In [76]:
#get index 0 of 0th and 1st dim and all values of 2nd dim
x[0,0,:]

tensor([1, 2, 3])

In [77]:
x[:,:,2]

tensor([[3, 6, 9]])

### Pytorch tensors and NumPy

NumPy is a popular scientific python numerical computing library

And because of this PyTorch has functionality to interact with it

* Data in numpy array, want in pytorch tensor (torch.from_numpy(ndarray)) [ndarray is numpy's default datatype like tensor is pytorch's]
* Pytorch tensor to numpy (torch.Tensor.numpy())

In [78]:
#numpy array to tensor
array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [79]:
array.dtype, tensor.dtype #NOTE pytorch's default dtype is float32 not 64

(dtype('float64'), torch.float64)

In [80]:
torch.arange(1.0,8.0).dtype

torch.float32

In [81]:
#if you want to chnage type of tensor created from numpy
tensor = torch.from_numpy(array).type(torch.float32)
tensor.dtype

torch.float32

In [82]:
#Change the value of array what will this do to tensor?
array=array+1
array, tensor #new tensor memory

(array([2., 3., 4., 5., 6., 7., 8.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [83]:
#tensor to numpy array

tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor, tensor.dtype, numpy_tensor.dtype

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32),
 torch.float32,
 dtype('float32'))

In [84]:
#change the tensor, what happens to numpy arrau
tensor = tensor +1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

### Pytorch Reproducibility (Tying to take the random out of random)

How a NN learns:
`start with random numbers-> tensor operations -> update random numbers to try and make them a better representation of data -> again -> again -> again...`

How to make the results reproducible EXACTLY?

To reduce the randomnes in NN and PyTorch, comes the concept of a *random seed*. Essentially what random seed does is "flavour" the randomness.

In [85]:
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)
random_tensor_A, random_tensor_B, random_tensor_A==random_tensor_B

(tensor([[0.7138, 0.7115, 0.7410, 0.1107],
         [0.6010, 0.3761, 0.8070, 0.4447],
         [0.4158, 0.2788, 0.4852, 0.1259]]),
 tensor([[0.4437, 0.7142, 0.5382, 0.9030],
         [0.7631, 0.6313, 0.8458, 0.6884],
         [0.6650, 0.5164, 0.6696, 0.5194]]),
 tensor([[False, False, False, False],
         [False, False, False, False],
         [False, False, False, False]]))

In [86]:
# Let's make some random but reproducible tensors

RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)

random_tensor_C = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED) #needed everytime!!!!!
random_tensor_D = torch.rand(3,4)
random_tensor_C, random_tensor_D, random_tensor_C==random_tensor_D

(tensor([[0.8823, 0.9150, 0.3829, 0.9593],
         [0.3904, 0.6009, 0.2566, 0.7936],
         [0.9408, 0.1332, 0.9346, 0.5936]]),
 tensor([[0.8823, 0.9150, 0.3829, 0.9593],
         [0.3904, 0.6009, 0.2566, 0.7936],
         [0.9408, 0.1332, 0.9346, 0.5936]]),
 tensor([[True, True, True, True],
         [True, True, True, True],
         [True, True, True, True]]))

In [87]:
torch.rand(3,4)


tensor([[0.8694, 0.5677, 0.7411, 0.4294],
        [0.8854, 0.5739, 0.2666, 0.6274],
        [0.2696, 0.4414, 0.2969, 0.8317]])

In [88]:
torch.rand(3,4)


tensor([[0.1053, 0.2695, 0.3588, 0.1994],
        [0.5472, 0.0062, 0.9516, 0.0753],
        [0.8860, 0.5832, 0.3376, 0.8090]])

In [89]:
torch.manual_seed(RANDOM_SEED)
torch.rand(3,4)


tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

https://pytorch.org/docs/stable/notes/randomness.html

### Different ways of Accessing GPUs in Pytorch

Running tensors and Pytorch objects on GPUs (and making faster computations)
GPUs == faster computation on numbers, thanks to CUDA + NVIDIA hardware + pytorch working behind the scenes to make everything hunky dory

1. google Colab
2. Own
3. cloud computing (GCP, AWS, Azure)

In [90]:
### getting a GPU

In [91]:
!nvidia-smi

Mon Mar 18 02:14:53 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   51C    P8              10W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [92]:
## check for gpu access for pytorch
torch.cuda.is_available() #cuda is nvidia's  programming interface

True

In [95]:
## setup device agnostic code (whereever you run your code, gpu may not be available)
device = 'cuda' if torch.cuda.is_available() else 'cpu'
device

'cuda'

In [96]:
# count number of devices(gpus)
torch.cuda.device_count()

1

### Putting tensors (and models) on GPUs


In [98]:
#create a tensor, degfault is on cpu
tensor = torch.tensor([1,2,3])
# tensor = torch.tensor([1,2,3], device='cpu')
#tensor not on GPU
tensor, tensor.device

(tensor([1, 2, 3]), device(type='cpu'))

In [101]:
#move tensor to GPU if available
tensor_on_gpu = tensor.to(device)
tensor_on_gpu #0 is the index of gpu we are using

tensor([1, 2, 3], device='cuda:0')

In [105]:
# moving tensors back to cpu (eg: numpy only works on cpu)

# tensor_on_gpu.numpy() ### ERROR
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

(array([1, 2, 3]), tensor([1, 2, 3], device='cuda:0'))

In [106]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')